theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
true-color = true
undercurl = true
end-of-line-diagnostics = "error"
completion-replace = true
popup-border = "all"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "file-modification-indicator"]
center = ["file-name", "version-control"]
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type"
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
goto-reference-include-declaration = false
display-inlay-hints = true
display-progress-messages = true

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.smart-tab]
supersede-menu = true

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal.backspace]
f = [
  ":sh rm -f /tmp/unique-ca1ea106",
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-ca1ea106',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ":open %sh{cat /tmp/unique-ca1ea106}",
  ":redraw",
  ":set mouse false",
  ":set mouse true",
]

g = [
  ":insert-output lazygit >/dev/tty",
  ":redraw",
  ":set mouse false",
  ":set mouse true",
]
